-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 96fb7fa10f2f4c11ed33482a9ad7474251e5e97f
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: trailing-whitespace
        args:
        - --no-markdown-linebreak-ext
    -   id: check-xml
    -   id: check-yaml
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: v1.0.0
    hooks:
    -   id: remove-crlf
        exclude: npp/.*.xml
    -   id: remove-tabs
