-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: c2992bd3a11e3c0c2533ee370c26ac2b12d3a1b3
    hooks:
    -   id: check-json
    -   id: trailing-whitespace
        args:
        - --no-markdown-linebreak-ext
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: 181a63c511691da58116fa19a7241956018660bc
    hooks:
    -   id: remove-crlf
        exclude: npp/shortcuts.xml
    -   id: remove-tabs
-   repo: local
    hooks:
    -   id: do_not_commit_unmerged
        name: Block if string "<<< HEAD" is found
        entry: DO NOT COMMIT UNMERGED
        language: pcre
        exclude: .pre-commit-config.yaml
        files: ''
