- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: cedcea550c495d536247ca23115035b17074cac7
  hooks:
  - id: trailing-whitespace
  - id: check-json
- repo: git://github.com/Lucas-C/pre-commit-hooks
  sha: 9822cc88c700eacf9fae27d8d1f44fd309e25cca
  hooks:
  - id: remove-crlf
