-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 0d88124ef6343fbbc6c9d2872853f73546c98a3f
    hooks:
    -   id: check-json
    -   id: trailing-whitespace
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: 1320d84cf315728e6ac6cca83bd80e3c732f53df
    hooks:
    -   id: remove-crlf
    -   id: forbid-tabs
-   repo: local
    hooks:
    -   id: do_not_commit_unmerged
        name: Block if string "<<< HEAD" is found
        entry: DO NOT COMMIT UNMERGED
        language: pcre
        exclude: .pre-commit-config.yaml
        files: ''
