- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: cf550fcab3f12015f8676b8278b30e1a5bc10e70
  hooks:
  - id: check-json
  - id: trailing-whitespace
- repo: git://github.com/Lucas-C/pre-commit-hooks
  sha: 36289c7ad32b317c98ad41fd48c7cb367145588b
  hooks:
  - id: remove-crlf
  - id: forbid-tabs
- repo: local
  hooks:
  - id: do_not_commit
    name: Block if "DO NOT COMMIT" is found
    entry: DO NOT COMMIT
    language: pcre
    files: ''
