language: minimal
git:
  depth: 1
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages
notifications:
  email:
    on_success: never
