language: python
python: "3.7"
cache: pip
install: pip install pylint
script:
- pylint languages/python/*.py
- mv languages/web-d3/folded_puzzle.html .
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages
notifications:
  email:
    on_success: never
