language: minimal
git:
  depth: 1
script:
# Avoid error: The tag {% on line 18 in languages/web-d3/bookmarklets.md was not properly closed with %}
- rm languages/web-d3/bookmarklets.md
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages
notifications:
  email:
    on_success: never
